version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://user:password@postgres:5432/cinema_db
      - HASURA_URL=http://hasura:8080/v1/graphql
    depends_on:
      - postgres
      - hasura

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080/api

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cinema_db
    volumes:
      - ./hasura/migrations:/docker-entrypoint-initdb.d/migrations

  hasura:
    image: hasura/graphql-engine:v2.0.9
    ports:
      - "8080:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://user:password@postgres:5432/cinema_db
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=myadminsecretkey
    depends_on:
      - postgres
