-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE actors
-- ADD COLUMN created_at TIMESTAMP DEFAULT NOW(),
-- ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();
