-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO actors (name, bio, birthdate, created_at, updated_at)
-- VALUES
--     ('Leonardo DiCaprio', 'American actor and producer known for his work in movies like Titanic and Inception.', '1974-11-11', NOW(), NOW()),
--     ('Christian Bale', 'English actor known for his roles in Batman Begins and The Dark Knight.', '1974-01-30', NOW(), NOW()),
--     ('Bradley Cooper', 'American actor and filmmaker known for his roles in Silver Linings Playbook and American Sniper.', '1975-01-05', NOW(), NOW()),
--     ('Ryan Gosling', 'Canadian actor and musician known for his roles in La La Land and Drive.', '1980-11-12', NOW(), NOW()),
--     ('Vera Farmiga', 'American actress known for her roles in The Conjuring and Bates Motel.', '1973-08-06', NOW(), NOW());
