-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE actors (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     bio TEXT,
--     birthdate DATE
-- );
