-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO directors (name, bio, birthdate, created_at, updated_at)
-- VALUES
--     ('Christopher Nolan', 'British-American filmmaker known for his work on films like Inception and Interstellar.', '1970-07-30', NOW(), NOW()),
--     ('Christopher Nolan', 'British-American filmmaker known for his work on films like Inception and Interstellar.', '1970-07-30', NOW(), NOW()),
--     ('Todd Phillips', 'American filmmaker known for directing The Hangover series and Joker.', '1970-12-20', NOW(), NOW()),
--     ('Nicholas Sparks', 'American novelist and screenwriter known for his romantic novels adapted into films.', '1965-12-31', NOW(), NOW()),
--     ('James Wan', 'Malaysian-Australian filmmaker known for his work on The Conjuring series and Saw.', '1977-02-27', NOW(), NOW());
