-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- Grant CREATE privilege on the public schema
-- GRANT CREATE ON SCHEMA public TO cinema_user;
--
-- -- You may also need to grant USAGE privilege if it's not already present
-- GRANT USAGE ON SCHEMA public TO cinema_user;
